language: python
python:
  - 2.6
  - 2.7

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y swig libssl-dev krb5-user dnsutils

# install requirments
install:
 - pip install argparse
 - pip install python-ldap
 - pip install psycopg2
 - pip install M2Crypto

# run tests
script:
 - py.test ovirt_engine_kerbldap_migration/tests/

# notifications
notifications:
  email: false
