language: python
python:
  - 2.6
  - 2.7

# install requirments
install:
 - pip install argparse
 - pip install python-ldap
 - pip install psycopg2

# run tests
script:
 - py.test tests/

# notifications
notifications:
  email: false
